name: Rust

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-release:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Rust for Windows
      if: matrix.os == 'windows-latest'
      run: rustup default stable-x86_64-pc-windows-msvc

    - name: Build project
      run: cargo build --verbose --release

    - name: Create GitHub Release (only once)
      if: ${{ matrix.os == 'ubuntu-latest' }}
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: "Release ${{ github.run_number }}"
        draft: false
        prerelease: false

    - name: Upload Linux Binary
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: target/release/passhub_for_rspass
        asset_name: passhub_for_rspass_linux
        asset_content_type: application/octet-stream

    - name: Upload Windows Binary
      if: matrix.os == 'windows-latest'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url || steps.create_release.outputs.upload_url }}
        asset_path: target/release/passhub_for_rspass.exe
        asset_name: passhub_for_rspass_windows.exe
        asset_content_type: application/octet-stream
